/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import projetjava.Element;
import projetjava.Usine;

/**
 *
 * @author Julien Fayet
 */
public class AchatSupElem extends javax.swing.JFrame {
    private Usine usine;
    private String lasemaine;    /**
     * Creates new form AchatSupElem
     */
    public AchatSupElem(Usine usine,String semaine) {
        initComponents();
        this.usine=usine;
        this.lasemaine=semaine;
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnStock = new javax.swing.JButton();
        btnRetour = new javax.swing.JButton();
        btnAchat = new javax.swing.JButton();
        txtPrixSem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrixAct = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        listeElem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Prix de vente:");

        btnStock.setText("Voir stock");

        btnRetour.setText("Retour");

        btnAchat.setText("Acheter");

        jLabel3.setText("Prix d'achat actuel:");

        jLabel2.setText("Nom élément :");

        listeElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeElemActionPerformed(evt);
            }
        });

        jLabel1.setText("Prix des éléments par semaine");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrixAct)
                    .addComponent(txtPrixSem)
                    .addComponent(listeElem, 0, 160, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(216, 216, 216))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(133, 133, 133)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(btnRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(34, 34, 34)))
                            .addComponent(btnAchat, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                    .addGap(34, 34, 34)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(listeElem)
                .addGap(47, 47, 47)
                .addComponent(txtPrixAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrixSem))
                .addGap(104, 104, 104))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(37, 37, 37)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(39, 39, 39)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(129, 129, 129)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAchat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(22, 22, 22)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listeElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeElemActionPerformed
        // TODO add your handling code here:
        maGestionDeLevenement(evt);
    }//GEN-LAST:event_listeElemActionPerformed

  
    private void maGestionDeLevenement(ActionEvent evt) {
        String nom=listeElem.getSelectedItem().toString();
        Element objElement=new Element();
        for(Element e:usine.getElements()){
            if(e.getNom().equals(nom))
                objElement=e;
        }
        txtPrixAct.setText(objElement.getCode());
        
        String semaine=lasemaine;
        double prix=0;
        for(String s:usine.getListePrixE().keySet()){
            if(s.equals(semaine))
                if(usine.getListePrixE().get(s).get(objElement.getCode())!=null){
                    prix=usine.getListePrixE().get(s).get(objElement.getCode());
                }
                else{
                    prix=objElement.getAchat();
                }
                
        }
        txtPrixSem.setText(Double.toString(prix));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAchat;
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> listeElem;
    private javax.swing.JTextField txtPrixAct;
    private javax.swing.JTextField txtPrixSem;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        for(Element e:usine.getElements()){
            listeElem.addItem(e.getNom());
        }
        String nom=listeElem.getSelectedItem().toString();
        Element objElement=new Element();
        for(Element e:usine.getElements()){
            if(e.getNom().equals(nom))
                objElement=e;
        }
        txtPrixAct.setText(objElement.getCode());
        
        String semaine=lasemaine;
        double prix=0;
        for(String s:usine.getListePrixE().keySet()){
            if(s.equals(semaine))
                if(usine.getListePrixE().get(s).get(objElement.getCode())!=null){
                    prix=usine.getListePrixE().get(s).get(s);
                }
                else{
                    prix=objElement.getAchat();
                }
                
        }
        txtPrixSem.setText(Double.toString(prix));
    }

}
