/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import projetjava.Calcul;
import projetjava.Chaine;
import projetjava.Element;
import projetjava.FichierCSV;
import projetjava.GererFichier;
import projetjava.Production;
import projetjava.ProductionSemaine;
import projetjava.Usine;

/**
 *
 * @author Julien Fayet
 */
public class ProdSemaine extends javax.swing.JFrame {
    private int nb;
    private Usine usine;
    
    /**
     * Creates new form ProductionSemaine
     */
    public ProdSemaine(int nb,Usine usine) {
        initComponents();
        this.nb=nb;
        this.usine=usine;
        setComponents(nb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listeSemaine = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        listeChaines = new javax.swing.JComboBox<>();
        NiveauA = new javax.swing.JLabel();
        txtNiveauA = new javax.swing.JTextField();
        btnRetour = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        btnVoirProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ajout de production par semaine");

        jLabel2.setText("Choisir semaine : ");

        listeSemaine.setPreferredSize(new java.awt.Dimension(10, 22));
        listeSemaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeSemaineActionPerformed(evt);
            }
        });

        jLabel3.setText("Chaine : ");

        listeChaines.setPreferredSize(new java.awt.Dimension(10, 22));
        listeChaines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeChainesActionPerformed(evt);
            }
        });

        NiveauA.setText("Niveau d'activité : ");

        btnRetour.setText("Retour");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnStock.setText("Stock");
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        btnVoirProd.setText("Verifier Production");
        btnVoirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NiveauA)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNiveauA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listeChaines, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listeSemaine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(123, 123, 123))))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnRetour)
                .addGap(32, 32, 32)
                .addComponent(btnAjouter)
                .addGap(18, 18, 18)
                .addComponent(btnStock)
                .addGap(30, 30, 30)
                .addComponent(btnVoirProd)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listeSemaine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(listeChaines, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NiveauA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNiveauA))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetour)
                    .addComponent(btnAjouter)
                    .addComponent(btnStock)
                    .addComponent(btnVoirProd))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listeSemaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeSemaineActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_listeSemaineActionPerformed

    private void listeChainesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeChainesActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_listeChainesActionPerformed

    private void btnVoirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoirProdActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_btnVoirProdActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_btnRetourActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_btnAjouterActionPerformed

 private void maGestionDeLEvenement(ActionEvent evt) {
        Object source = evt.getSource();
        //GererFichier objFichier=new FichierCSV();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy ");
                Date date = new Date();
        if(source ==btnAjouter){
            if(txtNiveauA.getText().equals("")){
               JOptionPane.showMessageDialog(null,"Veuillez rentrez un niveau de production") ;
          }
          else{
               int niveau=Integer.parseInt(txtNiveauA.getText());        
               ArrayList<Chaine> lesChaines=usine.getChaineProd();
               Chaine laChaine=lesChaines.get(0);
               for(Chaine c:lesChaines){
                    if(c.getNom().equals(listeChaines.getSelectedItem().toString()))
                        laChaine=c;
                    }
                Calcul objCalcul=new Calcul();
                Production objProd=objCalcul.creerProd(laChaine,niveau);
                if(objProd==null){
                    JOptionPane.showMessageDialog(null,"Il est impossible de créer ce produit");
                }
                else{
                    System.out.println(objProd.getObjElement().getNom());
                ArrayList<ProductionSemaine> listeProdSemaine=usine.getListeProdSemaine();
                boolean existe=false;
                ProductionSemaine objProdSemaine = new ProductionSemaine();
                
                if(listeProdSemaine.isEmpty()){
                    System.out.println("listeVide");
                    ArrayList<Production> listeDeProd=new ArrayList<Production>();
                    listeDeProd.add(objProd);
                    date.setDate(date.getDate()+(7*listeSemaine.getSelectedIndex()));
                    String dateA=dateFormat.format(date);
                    ProductionSemaine objProdSem=new ProductionSemaine(listeSemaine.getSelectedItem().toString(),dateA,listeDeProd);
                    System.out.println(objProdSem.getDate());
                    listeProdSemaine.add(objProdSem);
                    //objFichier.setProdSemaine(listeProdSemaine);
                }
                else{
                    
                for(ProductionSemaine p:listeProdSemaine){
                    System.out.println("Récupérer chaine qui correspond");
                    if(p.getNomSemaine().equals(listeSemaine.getSelectedItem().toString())){
                        existe=true;
                        objProdSemaine=p;
                    }
                }
                if(existe==true){
                    System.out.println(objProd.getObjElement()+"test");
                    System.out.println(objProdSemaine.getNomSemaine());                    
                    objProdSemaine.ajouterProd(objProd);
                }
                else{
                ArrayList<Production> listeDeProd=new ArrayList<Production>();
                listeDeProd.add(objProd);
                date.setDate(date.getDate()+(7*listeSemaine.getSelectedIndex()));
                String dateA=dateFormat.format(date);
                objProdSemaine=new ProductionSemaine(listeSemaine.getSelectedItem().toString(),dateA,listeDeProd);
                System.out.println(objProdSemaine.getDate());
                listeProdSemaine.add(objProdSemaine);
                //objFichier.setProdSemaine(listeProdSemaine);
                }
                }}
          }
        }
        
        if(source==btnRetour){
            this.dispose();
        }
        if (source == btnStock) {
            JOptionPane.showMessageDialog(null,"Vous avez ouvert le stock") ; 
            Stock laFenetreAction;;
	    laFenetreAction= new Stock(usine);
            laFenetreAction.setVisible(true);
        }
        if(source == btnVoirProd){
            ArrayList<ProductionSemaine> listeP=usine.getListeProdSemaine();
            if(listeP.isEmpty()){
                JOptionPane.showMessageDialog(null,"Impossible, il n'y à pas de production de prévue") ; 
            }
            else{
                JOptionPane.showMessageDialog(null,"Vous avez ouvert les productions") ; 
                VoirProductionSemaine laFenetreVoirProd;
                laFenetreVoirProd= new VoirProductionSemaine(usine);
                laFenetreVoirProd.setVisible(true);
            }
            
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NiveauA;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnVoirProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> listeChaines;
    private javax.swing.JComboBox<String> listeSemaine;
    private javax.swing.JTextField txtNiveau;
    private javax.swing.JTextField txtNiveau1;
    private javax.swing.JTextField txtNiveauA;
    // End of variables declaration//GEN-END:variables

    private void setComponents(int nb) {
        
        for(Chaine c:usine.getChaineProd()){
            listeChaines.addItem(c.getNom());
        }
        
        for(int i=1;i<=nb;i++){
            listeSemaine.addItem("Semaine "+i);
        }
        
    }
}
